apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-vk-hack
  namespace: argocd
spec:
  project: vk-hackathon-apps
  source:
    repoURL: 'https://secure-messages.github.io/charts/'
    chart: 'python-app-chart'
    targetRevision: '0.1.3'
    helm:
      values: |
        replicaCount: 1
        image:
          repository: nolabelregistry/backend_vk_hack
          pullPolicy: Always
          tag: dev
        imagePullSecrets:
          - name: dockerhub-secret
        nameOverride: "backend-vk-hack"
        fullnameOverride: "backend-vk-hack"
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
        resources:
           limits:
             cpu: 400m
             memory: 600Mi
           requests:
             cpu: 300m
             memory: 300Mi
        env:
          - name: APP_HOST
            value: "0.0.0.0"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: "postgresql-vk-hack"
          - name: POSTGRES_PASSWORD
            value: "hackme"
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_DB
            value: "vk_hack_db"
          - name: VKMA_SERVICE_KEY
            value: "2209112e2209112e2209112ec321299014222092209112e4501e6585535b8190103f0a6"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vk-hackathon-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
