#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: nginx-app
#  namespace: nginx-app
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    acme.cert-manager.io/http01-ingress-class: "nginx"
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: nginx-app.sm2.fun
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: kube-prometheus-stack-grafana
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - grafana.sm2.fun
#      secretName: grafana-tls


